spring:
  application:
    name: Hask Task
  datasource:
    url: jdbc:postgresql://localhost:5432/hask_task
    # url: jdbc:postgresql://database-2.ccg66chzdfr3.us-east-2.rds.amazonaws.com:5432/auto_mobiles
    username: postgres
    password: postgres1
    driver-class-name: org.postgresql.Driver
    name: hask_task

  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # For Apache Kafka
#  kafka:
#    bootstrap:
#      servers: localhost:9092  # Address of your Kafka broker
#    consumer:
#      group:
#        id: task-consumer-group    # Consumer group for this app
#      auto-offset-reset: earliest      # Read from the earliest message if no offset exists
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer


# Display SpringDoc Swagger-Ui OpenAPI endpoint
springdoc:
  # Display spring-boot-actuator endpoints in SpringDoc Swagger-Ui
  show-actuator: true
  swagger-ui:
    # Display Swagger-Ui at the root endpoint
    defaultModelsExpandDepth: -1
    enabled: true
  api-docs:
    enabled: true


# Actuator Endpoints
management:
  server:
    port: 8181 # Changed Actuator Port from '8080' to '8181'
  endpoints:
    web:
        exposure:
            include: "*"


  # Write logs into library-api-steve.log file
logging:
  file:
    name: automobiles-api-steve.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  logback:
    rollingPolicy:
      max-history: 5
      max-file-size: 10MB


